const nodemailer = require('nodemailer');
const fs = require('fs');
const path = require('path');

async function sendDailyRadarEmail(newTracks = [], radarConfig = {}) {
  const secretsPath = path.resolve(__dirname, '../../configs/secrets.json');
  if (!fs.existsSync(secretsPath)) {
    console.error(`[Mailer] Error: Secrets file not found at ${secretsPath}. Skipping email.`);
    return false;
  }

  const secrets = JSON.parse(fs.readFileSync(secretsPath, 'utf8'));
  if (!secrets.gmailUser || !secrets.gmailAppPassword) {
    console.error("[Mailer] Error: Invalid secrets.json. Missing gmail credentials.");
    return false;
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: secrets.gmailUser,
      pass: secrets.gmailAppPassword
    }
  });

  const todayStr = new Date().toISOString().slice(0, 10);
  const trackCount = newTracks.length;

  if (trackCount === 0) {
    console.log("[Mailer] 0 qualifying tracks today. Preserving inbox silence (no email sent).");
    return true;
  }

  const isUS = radarConfig.market === 'US';
  const marketBadge = isUS ? '🇺🇸 US Indie Rock Radar' : '24-Hour Open-Web Indie Radar';
  const themeColor = isUS ? '#2563eb' : '#f97316';
  const emailTitle = isUS ? 'New Indie Live 24 — US Daily Radar' : 'New Indie Live 24 — Daily Dispatch';
  const subjectPrefix = isUS ? '[US RADAR]' : '[New Indie Live 24]';

  const subject = `${subjectPrefix} ${trackCount} Verified ${isUS ? 'US ' : ''}Indie Rock Drop${trackCount === 1 ? '' : 's'} Today! (${todayStr})`;

  const trackCardsHtml = newTracks.map(t => `
    <div style="background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 10px; padding: 16px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
      <div style="font-size: 1.15rem; font-weight: 700; color: #0f172a; margin-bottom: 6px;">
        ${t.artist} — ${t.title}
      </div>
      <div style="font-size: 0.88rem; color: #475569; margin-bottom: 8px;">
        <span style="background-color: #f1f5f9; color: #0f172a; padding: 2px 8px; border-radius: 4px; font-weight: 600;">📡 ${t.channel}</span>
        ${t.location ? `<span style="color: #64748b; margin-left: 6px;">📍 ${t.location}</span>` : ''}
        <span style="color: #94a3b8; margin-left: 6px;">(${t.releaseDate || todayStr})</span>
      </div>
      <div style="font-size: 0.85rem; color: #64748b; margin-bottom: 10px;">
        ${t.description || ''}
      </div>
      <div>
        <a href="${t.url}" target="_blank" style="display: inline-block; background-color: ${themeColor}; color: #ffffff; padding: 6px 14px; border-radius: 6px; text-decoration: none; font-size: 0.82rem; font-weight: 600;">
          ▶ Listen to Release
        </a>
      </div>
    </div>
  `).join('');

  const htmlContent = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 640px; margin: 0 auto; color: #1e293b; padding: 20px; line-height: 1.5;">
      <div style="border-bottom: 2px solid ${themeColor}; padding-bottom: 12px; margin-bottom: 20px;">
        <span style="font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.1em; color: ${themeColor}; font-weight: 700;">${marketBadge}</span>
        <h2 style="color: #0f172a; margin: 4px 0 6px 0;">${emailTitle}</h2>
        <p style="color: #64748b; margin: 0; font-size: 0.95rem;">
          Verified <strong>${trackCount}</strong> brand-new ${isUS ? 'US ' : ''}release${trackCount === 1 ? '' : 's'} dropped within the last 24 hours.
        </p>
      </div>

      <div style="margin-bottom: 24px;">
        ${trackCardsHtml}
      </div>

      <p style="color: #94a3b8; font-size: 0.8rem; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 16px;">
        Generated by <strong>New Indie Live 24</strong> &bull; streamusique.com
      </p>
    </div>
  `;

  const mailOptions = {
    from: secrets.gmailUser,
    to: secrets.gmailUser,
    subject: subject,
    html: htmlContent
  };

  try {
    console.log(`[Mailer] Dispatching Daily Radar alert for ${trackCount} track(s)...`);
    const info = await transporter.sendMail(mailOptions);
    console.log("[Mailer] Alert sent successfully: " + info.response);
    return true;
  } catch (err) {
    console.error("[Mailer] Error sending email:", err.message);
    return false;
  }
}

module.exports = {
  sendDailyRadarEmail
};
